apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: webapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: cicdacr0701.azurecr.io/webapp1:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp1-svc
spec:
  selector:
    app: webapp1
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
